pipeline{
    agent any
    stages{
        stage('multistep stage'){
            steps{
                sh ' echo "This is multistep" '
                sh '''
                echo "By the way, I can do more stuff here"
                ls -lah
                '''
            }
        }
    }
}